#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $Dark_REPO == "DarkWeb" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RFQU1SRUJFTFMvUkVCRUxVU0VSQk9UL2FyY2hpdmUvUkVCRUwuemlw" | base64 -d
    elif [[ $Dark_REPO == "DarkWeb" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RFQU1SRUJFTFMvUkVCRUxVU0VSQk9UL2FyY2hpdmUvUkVCRUwuemlw" | base64 -d
    elif [[ $Dark_REPO =~ $regex ]]
    then
        if [[ $Dark_REPO_BRANCH ]]
        then
            echo "${Dark_REPO}/archive/${REBEL_REPO_BRANCH}.zip"
        else
            echo "${Dark_REPO}/archive/REBEL.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RFQU1SRUJFTFMvUkVCRUxVU0VSQk9UL2FyY2hpdmUvUkVCRUwuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="DarkWeb.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    DarkWebPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $DarkWebPATH
    echo "█▀▄ ▄▀█ █▀█ █▄▀ █░█░█ █▀▀ █▄▄   █▄▄ █▀█ ▀█▀
          █▄▀ █▀█ █▀▄ █░█ ▀▄▀▄▀ ██▄ █▄█   █▄█ █▄█ ░█░"

    python3 .../setup/updater.py .../requirements.txt requirements.txt
    python3 -m DarkWeb
}

_set_bot
